services:
  app:
    build: .
    env_file: [ ./.env.auth.local ]
    volumes: [ ./data:/data ]
    expose: [ "8501" ]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8501/_stcore/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    env_file: [ ./.env.auth.local ]
    command:
      - --provider=google
      - --http-address=0.0.0.0:4180
      - --upstream=http://app:8501
      - --email-domain=hua.gr
      - --redirect-url=http://localhost:8080/oauth2/callback
      - --cookie-secure=false
      - --cookie-samesite=lax
      - --set-authorization-header=true
      - --pass-authorization-header=true
      - --pass-user-headers=true
      - --skip-jwt-bearer-tokens=true
      - --cookie-refresh=1h
      - --cookie-expire=8h
    ports: [ "8080:4180" ]
    depends_on:
      app:
        condition: service_started
